#include <stdio.h>
#include <stdlib.h>
#include <time.h>
int main()
{
    //Variable declaration
    int your_choice,comp_choice;
    int your_score=0,comp_score=0;
    int round;
    printf("\n");
    printf("-----WELCOME TO THE MOST BELOVED TIME PASS GAME-----\n");
    printf("\n");
    printf("---That's correct, ROCK PAPER SCISSOR----\n");
    printf("\n");
    printf("It consists of 5 rounds, and if you score more than computer\n");
    printf("YOU WIN\n");
    printf("or else you lose :(\n");
    printf("\n");
    printf("0 -> ROCK\n1 -> PAPER\n2 -> SCISSOR\n");
    printf("\n");
    srand(time(0));

    //Loop for rounds to play
    for(round=0;round<5;round++){
        printf("------ROUND-%d------\n",round+1);
        printf("\n");
        printf("Enter your Choice (0,1,2)->");
        scanf("%d",&your_choice);
        if(your_choice<0||your_choice>2){
            printf("INVALID, Please choose between 0,1 and 2.\n");
            round--;
            continue;
        }
        printf("\n");
        //random number generated by computer bwetween 0 and 2
        comp_choice= rand() % 3;
        //Instead of 0,1,2 computer's choice is given in the form of strings with the help of switch case.
        switch(comp_choice)
        {
            case 0:
                printf("Computer chose: Rock\n");
                break;

            case 1:
                printf("Computer chose: Paper\n");
                break;

            case 2:
                printf("Computer chose: Scissors\n");
                break;
        }
        //For computer's choice in the form of integer(0,1,2) use below line.
        //printf("Computer chose->%d\n",comp_choice);
        if(your_choice==comp_choice){
            printf("...ITS DRAW...");
            printf("\n");
        }
        
        else if(your_choice==0 && comp_choice==1){
            printf("Computer WIN (Paper covers Rock)\n");
            comp_score++;
            printf("\n");
        }
       
        else if(your_choice==0 && comp_choice==2){
            printf("YOU WIN\n");
            your_score++;
            printf("\n");
        }
        else if(your_choice==1 && comp_choice==0){
            printf("YOU WIN\n");
            your_score++;
            printf("\n");
        }
        else if(your_choice==1 && comp_choice==2){
            printf("Computer WIN (Scissors slice Paper)\n");
            comp_score++;
            printf("\n");
        }
        else if(your_choice==2 && comp_choice==0){
            printf("Computer WIN (Rock smashes Scissor)\n");
            comp_score++;
            printf("\n");
        }
        else if(your_choice==2 && comp_choice==1){
            printf("YOU WIN\n");
            your_score++;
            printf("\n");
        }
    }
    printf("\n");
    printf("ALL ROUNDS DONE, TIME FOR TOTAL SCORE-->\n");
    printf("YOUR SCORE AGAINST COMPUTER IS : %d\n",your_score);
    printf("COMPUTER'S SCORE AGAINST YOU IS : %d\n",comp_score);
    if(your_score>comp_score){
        printf("Your score is more than computer.\n");
        printf("-----YOU WIN-----\n");
    }
    else if(your_score<comp_score){
        printf("Computer's score is more than you.\n");
        printf(" YOU LOSE  :()");
        printf("Better luck next time"); 
    }
    else{
        printf("Match is DRAW...");
    }
    return 0;
}